<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

import { listProblemTestSets, listRejudgeTasks, rejudgeProblemBatch, rejudgeSubmission } from '@/services/admin'
import { getApiErrorMessage } from '@/services/http'
import { getProblems } from '@/services/problems'
import type { RejudgeTask, TestSetMetadata } from '@/types/admin'
import type { ProblemSummary } from '@/types/problem'

const tasks = ref<RejudgeTask[]>([]); const loading = ref(false); const error = ref(''); const pending = ref(false); const submissionId = ref(''); const problems = ref<ProblemSummary[]>([]); const problemId = ref<number>(); const testSets = ref<TestSetMetadata[]>([]); const testSetId = ref(''); let timer: ReturnType<typeof setInterval> | undefined
async function load(): Promise<void> { loading.value = true; error.value = ''; try { tasks.value = (await listRejudgeTasks()).items } catch (reason) { error.value = getApiErrorMessage(reason, '重判任务加载失败') } finally { loading.value = false } }
async function loadSets(): Promise<void> { testSetId.value = ''; testSets.value = problemId.value ? await listProblemTestSets(problemId.value) : [] }
async function single(): Promise<void> { if (!submissionId.value) { ElMessage.warning('请输入 Submission UUID'); return } pending.value = true; try { await rejudgeSubmission(submissionId.value); submissionId.value = ''; ElMessage.success('重判任务已创建'); await load() } catch (reason) { ElMessage.error(getApiErrorMessage(reason, '重判发起失败')) } finally { pending.value = false } }
async function batch(): Promise<void> { if (!problemId.value || !testSetId.value) { ElMessage.warning('请选择题目和测试集版本'); return } try { await ElMessageBox.confirm('批量重判会为该题全部历史正式提交创建新的判题快照，任务可能消耗大量计算资源。确认继续？', '高风险操作二次确认', { type: 'warning', confirmButtonText: '确认批量重判' }); pending.value = true; await rejudgeProblemBatch(problemId.value, testSetId.value); ElMessage.success('批量重判任务已创建'); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getApiErrorMessage(reason, '批量重判失败')) } finally { pending.value = false } }
function statusLabel(status: string): string { return { queued: '排队中', running: '执行中', completed: '已完成', completed_with_errors: '部分失败' }[status] ?? status }
onMounted(async () => { problems.value = (await getProblems({ page: 1, page_size: 100, sort: 'newest' })).items; await load(); timer = setInterval(() => { if (tasks.value.some((item) => ['queued', 'running'].includes(item.status))) void load() }, 5000) }); onBeforeUnmount(() => clearInterval(timer))
</script>
<template><section class="admin-page" aria-labelledby="rejudge-title"><header class="admin-page-header"><div><p class="eyebrow">REJUDGE CONTROL</p><h1 id="rejudge-title">重判中心</h1></div></header><ElAlert title="重判不会修改原提交，而是复用受控源码对象创建新的不可变判题快照；所有请求仍由 judge-service 执行。" type="info" show-icon /><div class="rejudge-forms"><section class="admin-panel"><h2>按 Submission 重判</h2><ElInput v-model="submissionId" placeholder="Submission UUID" aria-label="提交 UUID" /><ElButton type="primary" :loading="pending" @click="single">发起重判</ElButton></section><section class="admin-panel danger-panel"><h2>按题目批量重判</h2><ElSelect v-model="problemId" filterable placeholder="选择题目" @change="loadSets"><ElOption v-for="problem in problems" :key="problem.id" :label="`${problem.id}. ${problem.title}`" :value="problem.id" /></ElSelect><ElSelect v-model="testSetId" placeholder="选择已激活版本"><ElOption v-for="set in testSets.filter((item) => ['active', 'inactive'].includes(item.status))" :key="set.id" :label="`v${set.version} · ${set.status} · 引用 ${set.submission_reference_count}`" :value="set.id" /></ElSelect><ElButton type="danger" :loading="pending" @click="batch">批量重判</ElButton></section></div><h2 class="admin-section-title">任务状态</h2><ElSkeleton v-if="loading" :rows="6" animated /><ElAlert v-else-if="error" type="error" :title="error" /><ElEmpty v-else-if="!tasks.length" description="暂无重判任务" /><ElTable v-else :data="tasks"><ElTableColumn prop="id" label="任务" min-width="260" /><ElTableColumn prop="mode" label="类型" width="80" /><ElTableColumn prop="problem_id" label="题目" width="80" /><ElTableColumn label="状态" width="110"><template #default="scope"><ElTag :type="scope.row.status === 'completed' ? 'success' : scope.row.status === 'completed_with_errors' ? 'warning' : 'info'">{{ statusLabel(scope.row.status) }}</ElTag></template></ElTableColumn><ElTableColumn prop="total_count" label="总数" width="70" /><ElTableColumn prop="success_count" label="成功" width="70" /><ElTableColumn prop="failed_count" label="失败" width="70" /><ElTableColumn prop="running_count" label="执行中" width="80" /></ElTable></section></template>
