<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'

import { controlDiscussion, handleContentReport, listContentReports, listModerationQueue, moderateContent } from '@/services/admin'
import { getApiErrorMessage } from '@/services/http'
import type { ContentReport, ModerationQueueItem } from '@/types/admin'

const activeTab = ref('queue'); const queue = ref<ModerationQueueItem[]>([]); const reports = ref<ContentReport[]>([]); const loading = ref(false); const error = ref(''); const pending = ref('')
async function load(): Promise<void> { loading.value = true; error.value = ''; try { if (activeTab.value === 'queue') queue.value = (await listModerationQueue(1)).items; else reports.value = (await listContentReports(1, activeTab.value === 'pending-reports' ? 'pending' : undefined)).items } catch (reason) { error.value = getApiErrorMessage(reason, '审核数据加载失败') } finally { loading.value = false } }
async function review(item: ModerationQueueItem, status: 'approved' | 'rejected'): Promise<void> { pending.value = `${item.target_type}:${item.target_id}`; try { let reason: string | undefined; if (status === 'rejected') reason = (await ElMessageBox.prompt('请输入驳回原因', '内容审核', { inputPattern: /\S+/, inputErrorMessage: '驳回原因不能为空' })).value; await moderateContent(item.target_type, item.target_id, status, reason); ElMessage.success(status === 'approved' ? '内容已通过' : '内容已驳回'); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getApiErrorMessage(reason, '审核失败')) } finally { pending.value = '' } }
async function control(item: ModerationQueueItem, kind: 'pin' | 'lock'): Promise<void> { try { await controlDiscussion(item.discussion_id, kind === 'pin' ? { is_pinned: !item.is_pinned } : { is_locked: !item.is_locked }); ElMessage.success(kind === 'pin' ? '置顶状态已更新' : '锁帖状态已更新'); await load() } catch (reason) { ElMessage.error(getApiErrorMessage(reason, '操作失败')) } }
async function handle(report: ContentReport, status: 'resolved' | 'dismissed'): Promise<void> { try { const result = await ElMessageBox.prompt('请输入处理说明（可选）', status === 'resolved' ? '处理举报' : '驳回举报'); await handleContentReport(report.id, status, result.value); ElMessage.success('举报状态已更新'); await load() } catch (reason) { if (reason !== 'cancel' && reason !== 'close') ElMessage.error(getApiErrorMessage(reason, '举报处理失败')) } }
onMounted(load)
</script>
<template><section class="admin-page" aria-labelledby="moderation-title"><header class="admin-page-header"><div><p class="eyebrow">TRUST & SAFETY</p><h1 id="moderation-title">内容审核</h1></div></header><ElTabs v-model="activeTab" @tab-change="load"><ElTabPane label="待审核内容" name="queue" /><ElTabPane label="待处理举报" name="pending-reports" /><ElTabPane label="全部举报" name="reports" /></ElTabs><ElSkeleton v-if="loading" :rows="7" animated /><ElAlert v-else-if="error" type="error" :title="error"><template #default><ElButton @click="load">重试</ElButton></template></ElAlert><ElEmpty v-else-if="activeTab === 'queue' && !queue.length" description="没有待审核内容" /><div v-else-if="activeTab === 'queue'" class="moderation-list"><article v-for="item in queue" :key="`${item.target_type}-${item.target_id}`"><header><ElTag>{{ item.target_type === 'discussion' ? '讨论' : '评论' }}</ElTag><span>题目 #{{ item.problem_id }} · {{ item.author?.nickname ?? '已删除用户' }}</span><time>{{ new Date(item.created_at).toLocaleString() }}</time></header><h2 v-if="item.title">{{ item.title }}</h2><p>{{ item.content }}</p><footer><ElButton type="success" :loading="pending === `${item.target_type}:${item.target_id}`" @click="review(item, 'approved')">通过</ElButton><ElButton type="danger" @click="review(item, 'rejected')">驳回</ElButton><template v-if="item.target_type === 'discussion'"><ElButton @click="control(item, 'pin')">{{ item.is_pinned ? '取消置顶' : '置顶' }}</ElButton><ElButton @click="control(item, 'lock')">{{ item.is_locked ? '解锁' : '锁帖' }}</ElButton></template></footer></article></div><ElEmpty v-else-if="!reports.length" description="没有举报记录" /><ElTable v-else :data="reports"><ElTableColumn prop="id" label="编号" width="80" /><ElTableColumn prop="reason" label="举报原因" min-width="220" /><ElTableColumn label="目标" width="130"><template #default="scope">{{ scope.row.discussion_id ? `讨论 #${scope.row.discussion_id}` : `评论 #${scope.row.comment_id}` }}</template></ElTableColumn><ElTableColumn prop="status" label="状态" width="100" /><ElTableColumn label="操作" width="170"><template #default="scope"><template v-if="scope.row.status === 'pending'"><ElButton link type="primary" @click="handle(scope.row, 'resolved')">处理</ElButton><ElButton link @click="handle(scope.row, 'dismissed')">驳回</ElButton></template><span v-else>已完成</span></template></ElTableColumn></ElTable></section></template>
